# Generated by Django 4.0.4 on 2022-04-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_song_likes_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_image',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
