# Generated by Django 4.0.4 on 2022-04-28 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_song_album_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album_image',
        ),
    ]
