# Generated by Django 4.0.4 on 2022-04-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_song_album_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album_image',
            field=models.CharField(max_length=500),
        ),
    ]
